name: Publish dev nuget package to nuget.org

on:
  push:
    branches:
      - v*

jobs:
  build:
    runs-on: windows-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100

      - uses: aarnott/nbgv@master
        with:
          setAllVars: true

      - run: echo "NBGV_SemVer2 $ENV:NBGV_SemVer2"

      - name: pack
        run: |
          cd $ENV:GITHUB_WORKSPACE/src
          dotnet pack --configuration Release -o . -p:PackageVersion=$ENV:NBGV_SemVer2

      - name: Push nuget package to nuget.org registry
        run: |
          cd $ENV:GITHUB_WORKSPACE/src
          dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --no-symbols --skip-duplicate --source https://api.nuget.org/v3/index.json
